# Generate a changelog with semantic-release
# Skip if the commit message is "Initial commit"
on:
  push:
    branches:
      - em1-converter-ebuy
jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, 'Initial commit')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
      - name: Show working copy
        run: ls -la && git status