name: Undeploy Converter Branches

on:
  schedule:
    # every day at 00:00
    - cron:  '0 0 * * *'
  push:
    branches: 
      - em1-converter-ebuy

jobs:
  # undeploy any action in the "convert" package that is older then 5 days
  undeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: npm ci
    - run: npm run converter:undeploy -- convert github:open_pull_request
      env: 
        WSK_AUTH: ${{ secrets.WSK_AUTH }}
        WSK_NAMESPACE: ${{ secrets.WSK_NAMESPACE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
